# Generated by Django 4.2.1 on 2023-05-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City of a location')),
                ('state', models.CharField(max_length=255, verbose_name='State of a location')),
                ('zip_index', models.CharField(max_length=100, verbose_name='Zip of a location')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude of a location')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude of a location')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=5, verbose_name='License plate of a truck')),
                ('load_capacity', models.PositiveIntegerField(verbose_name='Load capacity of a truck')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location', verbose_name='Current location for a truck')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight of a cargo')),
                ('description', models.TextField(verbose_name='Description of a cargo')),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_locations', to='api.location', verbose_name='Delivery location for a cargo')),
                ('pick_up_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up_locations', to='api.location', verbose_name='Pickup location for a cargo')),
            ],
        ),
    ]
